version: "3.9"
services:
  api:
    container_name: flask-app
    build:
      context: .
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "flask db upgrade &&
             flask run -h 0.0.0.0 -p 80"
  db:
    container_name: postgres
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: flaskappuserdb
      POSTGRES_PASSWORD: dalprodal123
      POSTGRES_DB: questions
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d questions -U flaskappuserdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  postgres_data:


