version: "3.9"
services:
  api:
    container_name: $NAME_APP
    image: dalred/$NAME_APP:$GITHUB_REF_NAME-version-$GITHUB_RUN_ID
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "flask db upgrade &&
             flask run -h 0.0.0.0 -p 80"
  db:
    container_name: postgres
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $DB_NAME -U $DB_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  postgres_data:


