name: Build and deploy action
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  NAME_APP: ${{secrets.NAME_APP}}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: Echo gitHubname and repo
        run: echo ${{ github.repository }}/${{ github.ref_name }}/${{secrets.NAME_APP}}
      - name: 'Create env file'
        run: |
          touch .env
          echo client_id=${{ secrets.client_id }} >> .env
          echo client_secret=${{ secrets.client_secret }} >> .env
          echo access_token=${{ secrets.access_token }} >> .env
          cat .env
      - name: render config.py
        run: |
          cat docker_ci_config.py | envsubst > config.py
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.NAME_APP}}:${{ github.ref_name }}-version-${{ github.run_id }}
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
      - name: clone files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: $SSH_USERNAME
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deploy/docker-compose.yaml"
          target: ${{secrets.NAME_APP}}
          strip_components: 1
      - name: run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: $SSH_USERNAME
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo homepath $HOME
            cd ${{secrets.NAME_APP}}
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose down
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
